swiftapp/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.home, name='home'),
    path("register/", views.register, name="register"),
    path("login/", views.Login, name="login"),
    path("contact/", views.contact, name="contact"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("about/", views.about, name="about"),
    path("logout/", views.Logout, name="logout"),

    path("display/", views.display, name="display"),
    path('items/', views.items, name="items"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('export-excel', views.export_excel, name="export-excel"),

    path("password_reset/", auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="password_reset"),

    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
]

swiftproject/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler400, handler403, handler404 , handler500
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("swiftapp.urls"))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if not settings.DEBUG:
    handler400 = 'swiftapp.views.bad_request'
    handler403 = 'swiftapp.views.permission_denied'
    handler404 = 'swiftapp.views.page_not_found'
    handler405 = 'swiftapp.views.server_error'

swiftapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField
from cloudinary.models import CloudinaryField

# Create your models here.
class SwiftUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('You must provide an email address')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault('is_superuser',True)
        extra_fields.setdefault('is_admin',True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superusers must have is_staff = True')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_super = True')

        if extra_fields.get('is_admin') is not True:
            raise ValueError('Superuser must have is_admin = True')

        return self.create_user(email, password, **extra_fields)

class SwiftUser(AbstractUser):
    username = None
    email = models.CharField(max_length=225,unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    phone = models.CharField(verbose_name="mobile number", max_length=11, blank=True)
    avatar = CloudinaryField("avater")
    last_login = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)


    #def save(self, *args, **kwargs):
        #super().save(*args, **kwargs)
        #if self.is_superuser:
            #ShowElement.objects.update_or_create(defaults={'are_visible': self.toggle_status})


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password', 'phone','avatar', 'first_name', 'last_name']

    objects = SwiftUserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


#class ShowElement(models.Model):
    #are_visible = models.BooleanField(default=False)

class UserItems(models.Model):

    garri_list = [('',''),('Quarter(0.25)','Quarter(0.25)'), ('Half(0.5)','Half(0.5)'),('1-bag','1-bag'),('2-bag','2-bag'),('No','No')]
    rice_list = [('',''),('Quarter(0.25)','Quarter(0.25)'), ('Half(0.5)','Half(0.5)'),('1-bag','1-bag'),('2-bags','2-bags'),('No','No')]
    beans_list = [('',''),('Quarter(0.25)','Quarter(0.25)'), ('Half(0.5)','Half(0.5)'),('1-bag','1-bag'),('No','No')]
    red_oil_list = [('',''),('Quarter(0.25)','Quarter(0.25)'), ('Half(0.5)','Half(0.5)'),('1','1'),('2','2'),('No','No')]
    veg_oil_list = [('',''),('Quarter(0.25)','Quarter(0.25)'), ('Half(0.5)','Half(0.5)'),('1','1'),('2','2'),('No','No')]
    onions_list = [('',''),('Quarter(0.25)','Quarter(0.25)'), ('Half(0.5)','Half(0.5)'),('3-quarter(0.75)','3-quarter(0.75)'),('1', '1'), ('No','No')]
    #spaghetti_list = [('',''),('Half(0.5)','Half(0.5)'), ('1-Carton','1-Carton'), ('2-Cartons','2-Cartons'), ('3-Cartons','3-Cartons'),('No','No')]
    #noodle_list = [('',''),('1-carton','1-Carton'), ('2-Cartons','2-Cartons'),('3-Cartons','3-Cartons'),('No','No')]
    #yam_list = [('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4','4'), ('5', '5'), ('6', '6'), \
        #('7','7'), ('8', '8'),('9', '9'), ('10', '10'), ('11','11'), ('12','12'), ('13','13'), ('No','No'), ('not-available', 'not-available')]
    #tomatoe_satchet_list = [('',''),('1-carton','1-carton'),('2-cartons','2-cartons'),('3-cartons','3-cartons'),('No','No')]
    #tomatoe_list = [('',''),('Quarter(0.25)','Quarter(0.25)'),('Half(0.5)','Half(0.5)'),('1','1'),('2','2'),('No','No')]
    #semo_list = [('',''),('1-bag','1-bag'),('2-bag','2-bag'),('2-bag','2-bag'), ('No','No')]
    #duration_list = [('',''),('1st Quarter','1st Quarter'), ('2nd Quarter','2nd Quarter'), ('3rd Quarter','3rd Quarter'), ('4th Quarter','4th Quarter')]

    user = models.OneToOneField('SwiftUser', on_delete=models.CASCADE)
    white_garri_ijebu = models.CharField(choices=garri_list, null=True, blank=True, max_length=40)
    white_garri_bendel = models.CharField(choices=garri_list, null=True, blank=True, max_length=40)
    yellow_garri_bendel = models.CharField(choices=garri_list, null=True, blank=True, max_length=40)
    nig_rice = models.CharField(choices=rice_list, null=True, blank=True, max_length=40)
    foreign_rice_small_grain = models.CharField(choices=rice_list, null=True, blank=True, max_length=40)
    foreign_rice_big_grain = models.CharField(choices=rice_list, null=True, blank=True, max_length=40)
    honey_beans = models.CharField(choices=beans_list, null=True, blank=True, max_length=40)
    drum_beans = models.CharField(choices=beans_list, null=True, blank=True, max_length=40)
    pelebe_beans = models.CharField(choices=beans_list, null=True, blank=True, max_length=40)
    red_oil = models.CharField(choices=red_oil_list, null=True, blank=True, max_length=40)
    veg_oil = models.CharField(choices=veg_oil_list, null=True, blank=True, max_length=40)

    onions_big_size = models.CharField(choices=onions_list, null=True, blank=True, max_length=40)
    onions_gen_size = models.CharField(choices=onions_list, null=True, blank=True, max_length=40)
    #aunty_b_spag = models.CharField(choices=spaghetti_list, null=True, blank=True, max_length=40)
    #g_penny_spag = models.CharField(choices=spaghetti_list, null=True, blank=True, max_length=40)
    #crown_spag = models.CharField(choices=spaghetti_list, null=True, blank=True, max_length=40)
    #dangote_spag = models.CharField(choices=spaghetti_list, null=True, blank=True, max_length=40)
    #indomie_oriental = models.CharField(choices=noodle_list, null=True, blank=True, max_length=40)
    #indomie_chicken = models.CharField(choices=noodle_list, null=True, blank=True, max_length=40)
    #chikki_noodles = models.CharField(choices=noodle_list, null=True, blank=True, max_length=40)
    #mimee_noodles = models.CharField(choices=noodle_list, null=True, blank=True, max_length=40)
    #satchet_tomatoe = models.CharField(choices=tomatoe_satchet_list, null=True, blank=True, max_length=40)
    #tin_tomatoe_220g = models.CharField(choices=tomatoe_list, null=True, blank=True, max_length=40)
    #tin_tomatoe_450g = models.CharField(choices=tomatoe_list, null=True, blank=True, max_length=40)
    #semo = models.CharField(choices=semo_list, null=True, blank=True, max_length=40)
    #yam_tubers = models.CharField(choices=yam_list, null=True, blank=True, default='', max_length=40)
    #duration = models.CharField(choices=duration_list, null=True, blank=True, max_length=40)



    def __str__(self):
        return (
            f"{self.user.email}- White_garri_ijebu: {self.white_garri_ijebu}, White_garri_bendel: {self.white_garri_bendel},"
            f"Yellow_garri_bendel: {self.yellow_garri_bendel}, Nig_rice: {self.nig_rice}, Foreign_rice_small_grain: {self.foreign_rice_small_grain},"
            f"Foreign_rice_big_grain: {self.foreign_rice_big_grain}, Honey_beans: {self.honey_beans}, Drum_beans: {self.drum_beans},""Pelebe_beans:{self.pelebe_beans},"
            f"Red_oil: {self.red_oil},Veg_oil: {self.veg_oil}, Onions_big_size: {self.onions_big_size}, Onions_gen_size: {self.onions_gen_size}"

        )
        '''("
            f"Aunty_B_Spag: {self.aunty_b_spag}, G_penny_Spag: {self.g_penny_spag}, Crown_Spag: {self.crown_spag}, dangote_Spag: {self.dangote_spag},"
            f"Indomie_oriental: {self.indomie_oriental}, Indomie_chicken: {self.indomie_chicken}, Chikki_noodles: {self.chikki_noodles}, Mimee_noodles: {self.mimee_noodles},"
            f"Satchet_tomatoe: {self.satchet_tomatoe}, Tin_tomatoe_220g: {self.tin_tomatoe_220g}, Tin_tomatoe_450g: {self.tin_tomatoe_450g},Semo: {self.semo},"
            f"Yam_tubers: {self.yam_tubers}")'''

swiftapp/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>About - SwiftMart</title>{% endblock title %}

{% block content %}

   <div class="hero">

    </div>
    <div class="container">

        <div class="mt-4 about-wrapper">

            <div class="about-part1">
                <div class="card bg-light mb-3 border-light">

                    <div class="card-body flex flex-column text-center align-items-center">
                        <h3 class='about2'><span class="text-success">About</span> SwiftMart</h3>
                    </div>
                </div>
            </div>

            <div class="about-part2">
                <div class="card bg-light mb-3 border-light">

                    <div class="card-body flex flex-column user-data px-4">
                        <p class="about-text">
                            Welcome to SwiftMart, the ultimate solution for Swifttalk Limited's
                            staff to streamline their bulk food purchasing needs.
                            Designed with convenience in mind, SwiftMart offers an intuitive
                            platform where employees can securely login and effortlessly place
                            orders for their desired food items. We believe this simple website
                            can help to simplify the process of our food item purchase.
                            Join us at SwiftMart and experience a seamless way to shop for bulk
                            food items, tailored specifically for the Swifttalk Limited family.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

swiftapp/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Contact Us - SwiftMart</title>{% endblock title %}

{% block content %}

   <div class="contact-hero">
        <h2 id="contact-text"
            style="">
            Contact Us
        </h2>
    </div>

    <div class="container">


            <div class="row my-5">
                <div class="col-sm-6 col-lg-4 contact-col">
                    <div class="card mb-3 border-light contact-card">

                        <div class="card-body contact-card-body">
                            <h5 class='text-dark text-start'><i class="fa fa-home text-success icon"></i> Address</h5>
                            <p class="">3-6 Alhaji Adejumo Avenue,
                                Ilupeju Industrial Estate Ilupeju, Lagos.
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-4 contact-col">
                    <div class="card mb-3 border-light contact-card">
                        <div class="card-body contact-card-body">
                            <h5 class='text-dark text-start'><i class="fa fa-envelope text-success icon"></i> Email</h5>
                            <p class="">hr@swifttalk.net</p>
                            <span class="text-white">support@swifttalk.net</span>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-lg-4 contact-col">
                    <div class="card mb-3 border-light contact-card">
                        <div class="card-body contact-card-body">
                            <h5 class='text-dark text-start'><i class="fa fa-phone text-success icon"></i> Contact</h5>
                            <p class="">+2348060400050, +2347034534697</p>
                            <span class="text-white">+2348060400050, +2347034534697</span>
                        </div>
                    </div>

                </div>
            </div>

{% endblock content %}

swiftapp/templates/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %}<title> Dashboard Swiftmart </title>{% endblock title %}

{% block content %}

  <div class="pt-5 pb-5 container">
    {% if messages %}

      <div class="alert alert-success alert-dismissible" role="alert">
        {% for message in messages %}
          {{ message }}
            {% endfor %}
              <button class="btn-close alert-link" data-bs-dismiss="alert"></button>
      </div>

    {% endif %}


    <div class="row">

      <div class="col-sm-6 col-lg-4">
        <div class="card bg-light mb-3 border-light">
          <div class="card-header text-center mb-2"><h5 class='text-dark'>{{user.first_name}}'s Dashboard</h5></div>
            <div class="card-body flex flex-column user-data">
              <img src="{{ user.avatar.url }}" alt="profile-image" width="120px" height="100px" class="rounded-circle mb-2">
              <p class='text-start pt-2'><strong>Email: </strong>{{ user.email }}</p>
              <p class=""><strong>Phone: </strong>{{ user.phone }}</p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-lg-8">
          <div class="card bg-light mb-3 border-light">
            <div class="card-header text-center mb-2"><h5 class='text-dark'>
              My Items</h5>
            </div>

            {% for item in user_items %}

              <div class="card-body flex flex-column user-data px-4">

                <div class="container">

                  <div class="table-responsive">
                    <table class="table text-sm">
                      <thead>
                        <tr>
                          <th>Items</th>
                          <th>Quantity</th>
                          <th><a href="{% url 'edit' item.id %}" class="btn btn-success" style="font-size:0.8rem">Edit</a></th>
                        </tr>
                      </thead>

                      <tbody>

                        <tr>

                          <td>white-garri-Ijebu<small class="text-danger">-₦66,000</small></td>
                          <td>{{ item.white_garri_ijebu }}</td>
                        </tr>
                        <tr>
                          <td>white-garri-bendel<small class="text-danger">-₦52,000</small></td>
                          <td>{{ item.white_garri_bendel }}</td>
                        </tr>
                        <tr>
                          <td>Yellow-garri-bendel<small class="text-danger">-₦52,000</small></td>
                          <td>{{ item.yellow_garri_bendel }}</td>
                        </tr>
                        <tr>
                          <td>Rice(Nig)<small class="text-danger">-₦67,000</small></td>
                          <td>{{item.nig_rice}}</td>
                        </tr>
                        <tr>
                          <td>Foreign-rice-small-grain<small class="text-danger">-₦70,000</small></td>
                          <td>{{item.foreign_rice_small_grain}}</td>
                        </tr>
                        <tr>
                          <td>Foreign-rice-big-grain<small class="text-danger">-₦75,000</small></td>
                          <td>{{item.foreign_rice_big_grain}}</td>
                        </tr>
                        <tr>
                          <td>Honey-beans<small class="text-danger">-₦91,000</small></td>
                          <td>{{item.honey_beans}}</td>

                        </tr>
                        <tr>
                          <td>Drum-beans<small class="text-danger">-₦180,000</small></td>
                          <td>{{item.drum_beans}}</td>
                        </tr>
                        <tr>
                          <td>Pelebe-beans<small class="text-danger">-₦160,000</small></td>
                          <td>{{item.pelebe_beans}}</td>

                        </tr>
                        <tr>
                          <td>Red-oil<small class="text-danger">-₦30,000-25L</small></td>
                          <td>{{item.red_oil}}</td>
                        </tr>
                        <tr>
                          <td>Vegetable-oil<small class="text-danger">-₦52,000-25L</small></td>
                          <td>{{item.veg_oil}}</td>
                        </tr>



                        <tr>
                          <td>Onions-big-size<small class="text-danger">-₦45,000</small></td>
                          <td>{{item.onions_big_size}}</td>
                        </tr>
                        <tr>
                          <td>Onions-gen-size<small class="text-danger">-₦91,000</small></td>
                          <td>{{item.onions_gen_size}}</td>
                        </tr>
                        <tr>
                          <td>Aunty-b-spag</td>
                          <!--<td>{{item.aunty_b_spag}}</td>-->
                        </tr>
                        <tr>
                          <td>G-penny-spag</td>
                          <!--<td>{{item.g_penny_spag}}</td>-->
                        </tr>
                        <tr>
                          <td>Crown-spag</td>
                          <!--<td>{{item.crown_spag}}</td>-->
                        </tr>
                        <tr>
                          <td>Dangote-spaghetti</td>
                          <!--<td>{{item.dangote_spag}}</td>-->
                        </tr>
                        <tr>
                          <td>Noodles-indomie-oriental</td>
                          <!--<td>{{item.indomie_oriental}}</td>-->
                        </tr>
                        <tr>
                          <td>Noodles-indomie-chicken</td>
                          <!--<td>{{item.indomie_chicken}}</td>-->
                        </tr>
                        <tr>
                          <td>Noodles-chikki-chicken</td>
                          <!--<td>{{item.chikki_noodles}}</td>-->
                        </tr>
                        <tr>
                          <td>Noodles-mimee-chicken</td>
                          <!--<td>{{item.mimee_noodles}}</td>-->
                        </tr>

                        <tr>
                          <td>Satchet-tomatoe</td>
                          <!--<td>{{item.satchet_tomatoe}}</td>-->
                        </tr>
                        <tr>
                          <td>Tin-tomatoe-220g</td>
                          <!--<td>{{item.tin_tomatoe_220g}}</td><-->
                        </tr>
                        <tr>
                          <td>Tin-tomatoe-450g</td>
                          <!--<td>{{item.tin_tomatoe_450g}}</td><-->
                        </tr>
                        <tr>
                          <td>Semo</td>
                          <!--<td>{{item.semo}}</td><-->
                        </tr>
                        <tr>
                          <td>Yam</td>
                          <!--<td>{{item.yam_tubers}}</td>-->
                        </tr>

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

            {% endfor %}

            <div class="card-footer">
                <p>Back to <a class="text-success" href="{% url 'home'%}"> Home</a></p>
              </div>

          </div>
        </div>
      </div>

    </div>
  </div>

{% endblock content %}

swiftapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>Login - SwiftMart</title>{% endblock title %}

{% block content %}

    <br>
    <div class="row justify-content-center border-light mt-12">
        <div>
            {% if messages %}

                <div class="alert alert-success alert-dismissible" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    <button class="btn-close alert-link" data-bs-dismiss="alert"></button>
                </div>

            {% endif %}
        </div>

        <div class="col-sm-6 col-lg-5">
            <div class="card bg-light mb-3 border-light">
                <div class="card-header text-center mb-2  py-3"><h4 class='text-dark'>Hello! Welcome Back</h4></div>
                <div class="card-body">
                    <form method="POST" novalidate class="px-4 pb-3">
                        {% if login_form.non_field_errors %}
                            {% for error in login_form.non_field_errors  %}
                                <p class="text-danger" style="color:red;">{{error}}</p>
                            {% endfor %}
                        {% endif %}

                        {% csrf_token %}
                        <div class="form-group mb-4">
                             {{ login_form.email.label_tag }}

                            <input type="email" class="form-control" name="email" placeholder="Email">
                            {% for error in login_form.email.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group mb-4">
                            {{ login_form.password.label_tag }}
                             <input type="password" class="form-control" name="password" placeholder="Password">
                            {% for error in login_form.password.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>

                        <p class="forgot_password"><a href="{% url 'password_reset' %}" class="text-success forgot_password">Forgot Password?</a></p>
                        <button type="submit" class="btn btn-success w-100 mb-3" width="100%">Login</button>
                        <span class="mb-4">New to Swiftmart?  <a href="{% url 'register' %}" class="link-success">Create Account</a></span>

                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock content %}

swiftapp/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}<title>Password Reset - SwiftMartin</title>{% endblock title %}

{% block content %}


    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card bg-light border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                            <h4 class="font-weight-light my-2 text-center">Forgot Password?</h4>
                        </div>

                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong class="">{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="mb-1" for="id_email">Email</label>
                                            <input type="email" name="email"  class="form-control"
                                                autocomplete="email" maxlength="254" required id="id_email"
                                                placeholder="Enter email"
                                            >
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-lg-10 offset-md-1">
                                        <div class="form-group mt-4 mb-1">
                                            <button type="submit" class="w-100 btn btn-success">Submit
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="text-center pb-3">
                            <div class="py-1 font-xl text-start mx-5">
                                Click here to <a href="{% url 'login' %}" class="link-success">Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>


{% endblock content %}

swiftapp/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>Register - SwiftMart</title>{% endblock title %}

{% block content %}<br><br><br>



    <div class="row justify-content-center border-light mt-8">
        <div class="col-sm-6 col-lg-5 mt-5">
            <div class="card bg-light mb-3 border-light">
                <div class="card-header text-center mb-2 py-3">
                    <h5 class="text-dark">Staff Registration Form</h5>
                </div>
                <div class="card-body">
                    <form action="" method="POST" novalidate enctype="multipart/form-data" class="px-4 pb-3">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_firstname">First Name</label>
                            <input type="text" id="id_firstname" name="first_name" class="form-control mb-2" placeholder="Emmanuel">
                            {% for error in form.first_name.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group py-2">
                            <label for="id_lastname">Last Name</label>
                            <input type="text" id="id_lastname" name="last_name" class="form-control" placeholder="Mkpurunchi">
                            {% for error in form.last_name.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>

                        <div class="form-group py-2">
                            <label for="id_email">Email</label>
                            <input type="email" id="id_email" name="email" class="form-control" placeholder="emf0046@gmail.com">
                            {% for error in form.email.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group py-2">
                            <label for="id_phone">Phone Number</label>
                            <input type="tel" id="id_phone" name="phone" class="form-control" placeholder="07034534697">
                            {% for error in form.phone.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group py-2">
                            <label for="id_password1">Password</label>
                            <input type="password" id="id_password1" name="password1" class="form-control" placeholder="Password1">
                            {% for error in form.password1.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group py-2">
                            <label for="id_password2">Confirm Password</label>
                            <input type="password" id="id_password2" name="password2" class="form-control" placeholder="Password again">
                            {% for error in form.password2.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group py-2">
                            <label for="id_avatar">Profile Image</label>
                            <input type="file" id="id_avatar" name="avatar" class="form-control">
                            {% for error in form.avatar.errors %}
                                <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-success w-100 my-4" width="100%">Register</button>
                        <span class="">Already have an account <a href="{% url 'login' %}" class="link-success">Login</a></span>
                    </form>

                </div>
            </div>
        </div>
    </div>



{% endblock content %}